ALTER TABLE nodes ADD COLUMN total_ingress BIGINT DEFAULT 0;
ALTER TABLE nodes ADD COLUMN total_egress BIGINT DEFAULT 0;
ALTER TABLE nodes ADD COLUMN uptime BIGINT DEFAULT 0;
ALTER TABLE nodes ADD COLUMN last_session_ingress BIGINT DEFAULT 0;
ALTER TABLE nodes ADD COLUMN last_session_egress BIGINT DEFAULT 0;
