-- Backward-compat migration for older installs upgraded to current panel.
-- Ensures required node columns exist so reads/writes don't fail.

ALTER TABLE nodes ADD COLUMN IF NOT EXISTS root_password TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS join_token TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS auto_configure BOOLEAN DEFAULT FALSE;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS is_enabled BOOLEAN DEFAULT TRUE;

ALTER TABLE nodes ADD COLUMN IF NOT EXISTS country_code TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS flag TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

ALTER TABLE nodes ADD COLUMN IF NOT EXISTS reality_sni TEXT DEFAULT 'www.google.com';
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS load_stats TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS check_stats_json TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;

ALTER TABLE nodes ADD COLUMN IF NOT EXISTS config_qos_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS config_block_torrent BOOLEAN DEFAULT FALSE;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS config_block_ads BOOLEAN DEFAULT FALSE;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS config_block_porn BOOLEAN DEFAULT FALSE;

ALTER TABLE nodes ADD COLUMN IF NOT EXISTS last_latency DOUBLE PRECISION;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS last_cpu DOUBLE PRECISION;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS last_ram DOUBLE PRECISION;

ALTER TABLE nodes ADD COLUMN IF NOT EXISTS max_ram BIGINT DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS cpu_cores INTEGER DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS cpu_model TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS speed_limit_mbps INTEGER DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS max_users INTEGER DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS current_speed_mbps INTEGER DEFAULT 0;

ALTER TABLE nodes ADD COLUMN IF NOT EXISTS active_connections INTEGER DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS total_ingress BIGINT DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS total_egress BIGINT DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS uptime BIGINT DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS last_session_ingress BIGINT DEFAULT 0;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS last_session_egress BIGINT DEFAULT 0;

ALTER TABLE nodes ADD COLUMN IF NOT EXISTS doomsday_password TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS version TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS target_version TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS last_sync_trigger TEXT;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS is_relay BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE nodes ADD COLUMN IF NOT EXISTS pending_log_collection BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE nodes ADD COLUMN IF NOT EXISTS relay_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_nodes_relay_id'
    ) THEN
        ALTER TABLE nodes
            ADD CONSTRAINT fk_nodes_relay_id
            FOREIGN KEY (relay_id) REFERENCES nodes(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_nodes_join_token ON nodes(join_token);
CREATE INDEX IF NOT EXISTS idx_nodes_relay_id ON nodes(relay_id);
